name: qr_plus
description: Advanced all-in-one qr code package with support for safe qr codes.
version: 1.0.1
homepage: https://mankeli.co
repository: https://github.com/Mankeli-Software/qr_plus
issue_tracker: https://github.com/Mankeli-Software/qr_plus/issues
screenshots:
  - description: 'An example QR code rendered with QrPlusMode.paranoid'
    path: doc/asset/paranoid-qr.gif
  - description: 'An example QR code rendered with QrPlusMode.plain'
    path: doc/asset/plain-qr.jpg
publish_to: none

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  connectivity_plus: ^3.0.2
  encrypt: ^5.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  mobile_scanner: ^2.1.0
  ntp: ^2.0.0
  qr_flutter: ^4.0.0
  uuid: ^3.0.7

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  dart_code_metrics: any
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.0
  mankeli_analysis: ^1.1.0
  mocktail: ^0.3.0
  plugin_platform_interface: ^2.1.3

# package:derry scripts
scripts:
  gen:
    code: flutter pub run build_runner build --delete-conflicting-outputs

false_secrets:
  - /lib/src/model/src/qr_plus_mode.dart
  - /lib/src/model/src/qr_plus_mode.g.dart
  - /lib/src/model/src/qr_plus_mode.gen.dart
